In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/WEEK-4.1-CLASSIFICATION/1.GRID
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-4.1-CLASSIFICATION/1.GRID/Social_Network_Ads.csv")

Mounted at /content/gdrive
Grid-DT.ipynb	     Grid-RF.ipynb   Social_Network_Ads.csv
Grid-Logistic.ipynb  Grid-SVM.ipynb

In [2]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Reading the Dataset
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-4.1-CLASSIFICATION/1.GRID/Social_Network_Ads.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]}



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [8]:

re=grid.cv_results_
grid_predictions = grid.predict(X_test)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [9]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9108102345415777

In [10]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[78  7]
 [ 5 44]]

In [11]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        85
           1       0.86      0.90      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.91      0.90       134
weighted avg       0.91      0.91      0.91       134

In [12]:
table=pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001286,0.000240,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001348,0.000522,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.031376,0.002156,0.007092,0.001089,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.764706,0.789474,0.809524,0.820513,0.823529,0.801549,0.021953,8
3,0.263262,0.013393,0.018122,0.000983,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.800000,0.871795,0.809524,0.900000,0.923077,0.860879,0.048707,2
4,0.028980,0.002110,0.006718,0.001538,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.777778,0.809524,0.900000,0.944444,0.846349,0.064354,4
5,0.258450,0.003414,0.016687,0.000478,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.764706,0.871795,0.809524,0.900000,0.947368,0.858679,0.064796,3
6,0.001820,0.000812,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001495,0.000667,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.030239,0.002909,0.006205,0.000202,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.764706,0.742857,0.761905,0.900000,0.894737,0.812841,0.069445,7
9,0.293751,0.050262,0.017204,0.000767,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.764706,0.777778,0.809524,0.900000,0.947368,0.839875,0.071551,5
10,0.029883,0.004265,0.006073,0.000111,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.727273,0.842105,0.809524,0.900000,0.918919,0.839564,0.068510,6
11,0.363554,0.084413,0.021451,0.006083,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.800000,0.871795,0.790698,0.900000,0.947368,0.861972,0.059591,1

In [14]:
age_input=float(input("Age:"))
salary_input=float(input("Salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age:20
Salary:120
Sex Male 0 or 1:0

In [15]:
Future_Prediction=grid.predict([[age_input,salary_input,sex_male_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]