In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/WEEK-4.1-CLASSIFICATION/1.GRID
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-4.1-CLASSIFICATION/1.GRID/Social_Network_Ads.csv")

Mounted at /content/gdrive
Grid-DT.ipynb	     Grid-RF.ipynb   Social_Network_Ads.csv
Grid-Logistic.ipynb  Grid-SVM.ipynb

In [2]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Reading the Dataset
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-4.1-CLASSIFICATION/1.GRID/Social_Network_Ads.csv")
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']}



grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')

# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [8]:

re=grid.cv_results_
grid_predictions = grid.predict(X_test)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [9]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'random'}: 0.8507462686567164

In [10]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[75 10]
 [10 39]]

In [11]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.88      0.88      0.88        85
           1       0.80      0.80      0.80        49

    accuracy                           0.85       134
   macro avg       0.84      0.84      0.84       134
weighted avg       0.85      0.85      0.85       134

In [12]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

np.float64(0.8391356542617047)

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001199,0.000249,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.000804,0.000036,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.002822,0.000924,0.004750,0.000860,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.826263,0.846714,0.796284,0.869709,0.906166,0.849027,0.037411,3
3,0.002291,0.000086,0.005109,0.001188,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.808927,0.808392,0.815056,0.885265,0.811321,0.825792,0.029829,6
4,0.002897,0.000833,0.004854,0.000694,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.804764,0.828959,0.850543,0.832483,0.943699,0.852090,0.048071,2
5,0.002931,0.001050,0.004681,0.000705,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.869532,0.870047,0.738451,0.793565,0.906166,0.835552,0.060865,5
6,0.000760,0.000096,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001386,0.000613,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.002430,0.000415,0.004489,0.000664,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.829615,0.870047,0.777291,0.867097,0.844370,0.837684,0.033674,4
9,0.002161,0.000071,0.004218,0.000073,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.869532,0.793754,0.756031,0.756031,0.925272,0.820124,0.066945,8
10,0.002387,0.000345,0.004736,0.000342,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.808927,0.868752,0.795256,0.831098,0.808775,0.822562,0.025799,7
11,0.001930,0.000296,0.003686,0.000775,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.826263,0.850809,0.851527,0.868632,0.883278,0.856102,0.019157,1

In [15]:
age_input=float(input("Age:"))
salary_input=float(input("Salary:"))
sex_male_input=int(input("Sex Male 0 or 1:"))

Age:20
Salary:120
Sex Male 0 or 1:0

In [16]:
Future_Prediction=grid.predict([[age_input,salary_input,sex_male_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]