In [1]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/WEEK-3-ML/2.Grid

Mounted at /content/gdrive
DT_Grid.ipynb  insurance_pre.csv  RF_Grid.ipynb  SVR_Grid.ipynb

In [2]:
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-3-ML/2.Grid/insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=1)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [7]:
dep = dataset[['charges']]

In [8]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.30,random_state=0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {'criterion':['squared_error', 'absolute_error', 'friedman_mse'],'max_features': ['auto','sqrt','log2'],'splitter':['best', 'random']}


grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [12]:
re=grid.cv_results_

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002723,0.001091,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.001571,0.000477,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.008305,0.000483,0.004095,0.000593,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.736660,0.699917,0.636120,0.538304,0.716637,0.665528,0.071979,8
3,0.007404,0.000987,0.003755,0.000209,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.534184,0.608007,0.666819,0.623106,0.574962,0.601416,0.044747,12
4,0.008942,0.001245,0.003748,0.000197,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.636920,0.676564,0.589547,0.726214,0.661673,0.658184,0.045036,9
5,0.006668,0.001260,0.003780,0.000535,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.655855,0.634379,0.722904,0.649917,0.620136,0.656638,0.035397,10
6,0.001270,0.000118,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.001632,0.000862,0.000000,0.000000,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.028485,0.001358,0.003691,0.000080,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.783298,0.537034,0.731729,0.686013,0.666169,0.680849,0.082474,5
9,0.021538,0.001161,0.003795,0.000129,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.733462,0.675932,0.743158,0.718332,0.643851,0.702947,0.037435,2
10,0.028098,0.004112,0.004284,0.000713,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.741308,0.634814,0.731541,0.702063,0.747233,0.711392,0.041320,1
11,0.022339,0.002286,0.004100,0.000190,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.714478,0.606790,0.776811,0.628224,0.614295,0.668120,0.066653,7
12,0.002785,0.001040,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.002006,0.001655,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.007167,0.000293,0.003360,0.000092,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.757664,0.507373,0.691028,0.726287,0.711737,0.678818,0.088427,6
15,0.006448,0.000675,0.003540,0.000153,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.719588,0.558512,0.655759,0.699408,0.502406,0.627135,0.083495,11
16,0.008014,0.000692,0.003921,0.000697,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.788714,0.692569,0.597136,0.732733,0.666909,0.695612,0.064151,3
17,0.006802,0.000933,0.003637,0.000809,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.712221,0.672276,0.752040,0.705254,0.595917,0.687541,0.052366,4