In [23]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/WEEK-3-ML/2.Grid

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
DT_Grid.ipynb  insurance_pre.csv  RF_Grid.ipynb  SVR_Grid.ipynb

In [24]:
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-3-ML/2.Grid/insurance_pre.csv")

In [25]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [26]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=1)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [27]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [28]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [29]:
dep = dataset[['charges']]

In [30]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.30,random_state=0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error', 'absolute_error'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [32]:
re=grid.cv_results_

In [33]:
table=pd.DataFrame.from_dict(re)

In [34]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002367,0.000896,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001805,0.000605,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.051061,0.004391,0.007466,0.000834,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.835996,0.765340,0.829490,0.804214,0.831909,0.813390,0.026481,8
3,0.432186,0.006638,0.033694,0.013193,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858579,0.781974,0.856824,0.827170,0.842182,0.833346,0.028083,2
4,0.047621,0.002281,0.006380,0.000474,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.841213,0.754179,0.840771,0.813828,0.840212,0.818041,0.033589,6
5,0.435645,0.011488,0.026360,0.000325,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858000,0.781441,0.856840,0.828807,0.837533,0.832524,0.027888,4
6,0.001359,0.000070,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001657,0.000646,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.161394,0.012349,0.006885,0.000355,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.838927,0.763108,0.839599,0.809790,0.839849,0.818255,0.029873,5
9,1.452874,0.013377,0.025973,0.001194,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.853627,0.779355,0.861262,0.829700,0.844866,0.833762,0.029157,1
10,0.150707,0.005374,0.006792,0.001136,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.837097,0.766303,0.826121,0.818317,0.824112,0.814390,0.024801,7
11,1.252120,0.179490,0.021315,0.004187,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859145,0.774761,0.858499,0.830908,0.842801,0.833223,0.031067,3