In [37]:
from google.colab import drive
drive.mount('/content/gdrive')
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
!ls /content/gdrive/MyDrive/'Colab Notebooks'/'HOPE AI'/WEEK-3-ML/2.Grid

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
'Boosting Algorithm_Assignment.pdf'    DT_Grid.ipynb	   RF_Grid.ipynb
'Boosting Algorithm_Assignment.pptx'   insurance_pre.csv   SVR_Grid.ipynb

In [38]:
dataset = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/HOPE AI/WEEK-3-ML/2.Grid/insurance_pre.csv")

In [39]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [40]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=1)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [41]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [42]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [43]:
dep = dataset[['charges']]

In [44]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(indep,dep,test_size=0.30,random_state=0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {'criterion':['squared_error', 'absolute_error'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [46]:
re=grid.cv_results_

In [47]:
print("The R_score value for best parameter {}:".format(grid.best_params_))
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}:
Age:32
BMI:43
Children:2
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1
Future_Prediction=[43162.6466473]

In [48]:
table=pd.DataFrame.from_dict(re)

In [49]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003531,0.001298,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.004436,0.001953,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.094803,0.013639,0.012516,0.003851,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.824853,0.768395,0.837325,0.817151,0.819153,0.813375,0.023564,7
3,0.449462,0.017533,0.029272,0.002048,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.860079,0.778811,0.865450,0.828102,0.838247,0.834138,0.030880,1
4,0.048233,0.001321,0.006760,0.000400,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.848377,0.757140,0.844776,0.823161,0.818125,0.818316,0.032771,5
5,0.438725,0.006041,0.032330,0.012126,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856247,0.781197,0.859044,0.830926,0.839696,0.833422,0.028109,2
6,0.001654,0.000223,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.001683,0.000214,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.158493,0.005066,0.006533,0.000146,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.833493,0.758945,0.835930,0.803890,0.820876,0.810627,0.028230,8
9,1.515980,0.046062,0.029251,0.002526,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.855693,0.778662,0.857659,0.824654,0.845708,0.832475,0.029344,4
10,0.147711,0.003105,0.006544,0.000290,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.830905,0.765550,0.841131,0.806312,0.831621,0.815104,0.027323,6
11,1.585671,0.136741,0.030373,0.010502,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.858018,0.780522,0.852672,0.827377,0.847003,0.833118,0.028265,3